"""Proactive announcements composed from latest sensor data + forecast.

Each action evaluates a condition. If the condition is not met (e.g. "rain
reminder" but no rain on the way), `compose` returns None — the device or
dashboard caller should skip playback.

Phrasing is generated by Gemini so each announcement sounds natural rather
than reading a fixed template. The decision *whether* to speak stays in
Python so behaviour is predictable and testable.
"""
import os
import requests
from datetime import datetime, timezone, timedelta
from google.genai import types
from database import get_latest_row
from weather import get_forecast, parse_hourly_today, parse_daily_forecast
from voice import gen_client, MODEL

TZ_OFFSET  = timedelta(hours=int(os.environ.get("TZ_OFFSET_HOURS", "2")))
TRAIN_FROM = os.environ.get("TRAIN_FROM", "Genève")
TRAIN_TO   = os.environ.get("TRAIN_TO",   "Renens VD")

ACTIONS = (
    "motion",            # auto-pick most relevant given current context
    "current_summary",   # always speaks the current indoor/outdoor snapshot
    "morning_briefing",  # full briefing (conditions + today's forecast)
    "rain_reminder",     # only if rain on the way in next 6 h
    "humidity_alert",    # only if indoor humidity outside 30-70 %
    "air_quality_alert", # only if TVOC > 500 ppb or eCO2 > 1500 ppm
    "train_delay",       # only if morning trains are running late
)

SYSTEM = (
    "You are a friendly, concise voice for a home weather station. "
    "Given a structured context, produce ONE short sentence to be spoken "
    "aloud. Round numbers to one decimal place and always include units "
    "(°C, %, ppb, ppm). Vary phrasing across calls."
)


def _phrase(context: dict) -> str:
    user_text = (
        "Compose one short spoken sentence for this announcement.\n"
        f"Action: {context['action']}\n"
        f"Context: {context['context']}\n"
        f"Intent: {context['intent']}\n"
    )
    resp = gen_client.models.generate_content(
        model=MODEL,
        contents=[types.Content(role="user", parts=[types.Part.from_text(text=user_text)])],
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM,
            temperature=0.6,
        ),
    )
    return (resp.text or "").strip() or context["intent"]


def _rain_in_next_hours(hourly_today, hours=6):
    cutoff = datetime.now(timezone.utc) + TZ_OFFSET + timedelta(hours=hours)
    for h in hourly_today:
        if "rain" in h["description"].lower() or "drizzle" in h["description"].lower():
            try:
                h_time = datetime.strptime(h["time"], "%H:%M").time()
            except Exception:
                continue
            now = datetime.now(timezone.utc) + TZ_OFFSET
            slot = datetime.combine(now.date(), h_time)
            if now <= slot <= cutoff:
                return h
    return None


def _morning_window():
    now = datetime.now(timezone.utc) + TZ_OFFSET
    return 6 <= now.hour < 11


def _commute_window():
    """True during the morning commute window: 07:30 – 10:00."""
    now = datetime.now(timezone.utc) + TZ_OFFSET
    mins = now.hour * 60 + now.minute
    return 450 <= mins < 600  # 07:30 = 450, 10:00 = 600


def _delayed_trains(window_hours=2):
    """Return a list of delayed departures from TRAIN_FROM to TRAIN_TO
    within the next window_hours. Each entry: {time, delay (min), line}.
    Returns [] on any API or network error."""
    try:
        r = requests.get(
            "https://transport.opendata.ch/v1/connections",
            params={
                "from": TRAIN_FROM,
                "to":   TRAIN_TO,
                "transportations[]": "train",
                "limit": 8,
            },
            timeout=10,
        )
        data   = r.json()
        now    = datetime.now(timezone.utc) + TZ_OFFSET
        cutoff = now + timedelta(hours=window_hours)
        delayed = []
        for conn in data.get("connections", []):
            f       = conn.get("from") or {}
            dep_raw = f.get("departure") or ""
            delay_s = f.get("delay") or 0
            delay_m = int(delay_s) // 60 if delay_s else 0
            if delay_m <= 0 or len(dep_raw) < 16:
                continue
            try:
                dep_dt = datetime.fromisoformat(dep_raw)
                if now <= dep_dt <= cutoff:
                    line = ""
                    secs = conn.get("sections") or []
                    if secs and secs[0].get("journey"):
                        j    = secs[0]["journey"]
                        line = (j.get("name") or j.get("category") or "").strip()
                    delayed.append({"time": dep_raw[11:16], "delay": delay_m, "line": line})
            except Exception:
                continue
        return delayed
    except Exception:
        return []


def _compose_current_summary(latest):
    if not latest:
        return None
    ctx = {
        "indoor_temp":     latest["indoor_temp"],
        "indoor_humidity": latest["indoor_humidity"],
        "outdoor_temp":    latest["outdoor_temp"],
        "outdoor_weather": latest["outdoor_weather"],
    }
    return _phrase({
        "action":  "current_summary",
        "context": ctx,
        "intent":  "Briefly describe indoor and outdoor conditions right now.",
    })


def _compose_morning(latest, hourly):
    if not latest:
        return None
    rain          = _rain_in_next_hours(hourly, hours=12)
    train_delays  = _delayed_trains(window_hours=3)
    return _phrase({
        "action":  "morning_briefing",
        "context": {
            "indoor_temp":     latest["indoor_temp"],
            "indoor_humidity": latest["indoor_humidity"],
            "outdoor_temp":    latest["outdoor_temp"],
            "outdoor_weather": latest["outdoor_weather"],
            "rain_expected":   bool(rain),
            "rain_time":       rain["time"] if rain else None,
            "train_delays":    train_delays,
            "train_alert":     bool(train_delays),
        },
        "intent": (
            "Greet the user for the morning, summarize indoor and outdoor "
            "conditions, mention if rain is expected today. If train_alert is "
            "true, also warn that morning trains to Renens are delayed and "
            "state the worst departure time and delay in minutes."
        ),
    })


def _compose_rain(hourly):
    rain = _rain_in_next_hours(hourly, hours=6)
    if not rain:
        return None
    return _phrase({
        "action":  "rain_reminder",
        "context": {"rain_time": rain["time"], "description": rain["description"]},
        "intent":  "Warmly remind the user to take an umbrella; mention "
                   "approximately when rain is expected.",
    })


def _compose_humidity(latest):
    if not latest or latest.get("indoor_humidity") is None:
        return None
    h = latest["indoor_humidity"]
    if 30 <= h <= 70:
        return None
    intent = (
        "Alert that indoor air is too dry and suggest a glass of water or a "
        "humidifier."
        if h < 30 else
        "Alert that indoor humidity is high and suggest opening a window or "
        "running a fan."
    )
    return _phrase({
        "action":  "humidity_alert",
        "context": {"indoor_humidity": h},
        "intent":  intent,
    })


def _compose_air_quality(latest):
    if not latest:
        return None
    tvoc = latest.get("air_quality_tvoc") or 0
    eco2 = latest.get("air_quality_eco2") or 0
    if tvoc <= 500 and eco2 <= 1500:
        return None
    return _phrase({
        "action":  "air_quality_alert",
        "context": {"air_quality_tvoc": tvoc, "air_quality_eco2": eco2},
        "intent":  "Tell the user that indoor air quality has dropped and "
                   "suggest opening a window.",
    })


def _compose_train_delay():
    """Spoken alert if any trains on TRAIN_FROM→TRAIN_TO are delayed in the
    next 2 hours. Returns None when all trains run on time (→ no announcement)."""
    delayed = _delayed_trains(window_hours=2)
    if not delayed:
        return None
    worst = max(delayed, key=lambda d: d["delay"])
    return _phrase({
        "action":  "train_delay",
        "context": {
            "route":          f"{TRAIN_FROM} → {TRAIN_TO}",
            "delayed_trains": delayed,
            "worst_dep":      worst["time"],
            "worst_delay_min": worst["delay"],
        },
        "intent": (
            f"Alert the user that their train from {TRAIN_FROM} to {TRAIN_TO} "
            f"is running late. The {worst['time']} departure is delayed by "
            f"{worst['delay']} minutes. Be concise and mention the departure time."
        ),
    })


def compose(action: str):
    """Return the text to speak, or None if the action should be skipped."""
    if action not in ACTIONS:
        return None

    latest = get_latest_row()
    hourly = []
    if action in ("morning_briefing", "rain_reminder", "motion"):
        try:
            hourly = parse_hourly_today(get_forecast())
        except Exception:
            hourly = []

    if action == "current_summary":
        return _compose_current_summary(latest)
    if action == "morning_briefing":
        return _compose_morning(latest, hourly)
    if action == "rain_reminder":
        return _compose_rain(hourly)
    if action == "humidity_alert":
        return _compose_humidity(latest)
    if action == "air_quality_alert":
        return _compose_air_quality(latest)
    if action == "train_delay":
        return _compose_train_delay()

    # action == "motion": pick the most useful thing to say right now
    return (
        _compose_air_quality(latest)
        or _compose_humidity(latest)
        or (_compose_train_delay() if _commute_window() else None)
        or _compose_rain(hourly)
        or (_compose_morning(latest, hourly) if _morning_window() else None)
        or _compose_current_summary(latest)
    )
